name: DevSecOps Scan

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Install Trivy
        run: |
          curl -sfL https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/install.sh | sudo sh -s -- -b /usr/local/bin

      - name: Install Gitleaks
        run: |
          LATEST=$(curl -s https://api.github.com/repos/gitleaks/gitleaks/releases/latest | grep "tag_name" | cut -d '"' -f 4)
          wget https://github.com/gitleaks/gitleaks/releases/download/${LATEST}/gitleaks_${LATEST#v}_linux_x64.tar.gz
          tar -xzf gitleaks_${LATEST#v}_linux_x64.tar.gz
          sudo mv gitleaks /usr/local/bin/

      - name: Run Security Scans
        run: |
          PYTHONPATH=. python cli/main.py scan
          PYTHONPATH=. python scanner/report_builder.py
          PYTHONPATH=. python scanner/report_to_html.py

      - name: Upload HTML Report
        uses: actions/upload-artifact@v4
        with:
          name: scan-report
          path: reports/scan_report.html